##
## Service resource
## Distributes traffic to groups of pods and monitors their status. Kind of like a load balancer. 
##
apiVersion: v1
kind: Service
metadata:
  name: "bitcoin-core-22"
  namespace: "default"
spec:
  ports:
    - port: 8333
      targetPort: 8333
      protocol: TCP
  type: NodePort
  selector:
    app: "bitcoin-core-22"